MT.WebApp/Controllers/TableStoragesController.cs
using System;

using System.Linq;

using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using MT.AzureStorageLib.Entities;
using MT.AzureStorageLib.Services.Concrete;
using MT.AzureStorageLib.Services.Interfaces;

namespace MT.WebApp.Controllers
{
    public class TableStoragesController : Controller
    {
        private readonly TableStorage<UserPicture> _noSqlStorage;

        public TableStoragesController(TableStorage<UserPicture> noSqlStorage)
        {
            _noSqlStorage = noSqlStorage;
        }

        public IActionResult Index()
        {
            ViewBag.people = _noSqlStorage.All().ToList();
            ViewBag.IsUpdate = false;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(UserPicture person)
        {
        
            await _noSqlStorage.AddAsync(person);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Update(string rowKey, string partitionKey)
        {
            var product = await _noSqlStorage.GetAsync(rowKey, partitionKey);

            ViewBag.people = _noSqlStorage.All().ToList();
            ViewBag.IsUpdate = true;

            return View("Index", product);
        }

        [HttpPost]
        public async Task<IActionResult> Update(UserPicture person)
        {
            ViewBag.IsUpdate = true;

            await _noSqlStorage.UpdateAsync(person);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string rowKey, string partitionKey)
        {
            await _noSqlStorage.DeleteAsync(rowKey, partitionKey);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Query(string name)
        {
            ViewBag.IsUpdate = false;
            ViewBag.people = _noSqlStorage.Query(x => x.Name == name).ToList();

            return View("Index");
        }
    }
}

MT.WebApp/Views/TableStorages/Index.cshtml
@model MT.AzureStorageLib.Entities.UserPicture
<h2>Add Person</h2>
<form class="form-inline" asp-action="@(ViewBag.IsUpdate ? "Update" : "Create")" method="post" enctype="application/x-www-form-urlencoded">

    <input class="form-control mr-1" asp-for="RowKey" placeholder="User Id" />
    <input class="form-control mr-1" asp-for="PartitionKey" placeholder="City" />
    <input class="form-control mr-1" asp-for="Name" placeholder="Name" />


    <input type="hidden" asp-for="ETag" />
    <hr/>
    <input class=" btn btn-primary mt-2 mb-2" type="submit" value="@(ViewBag.IsUpdate ? "Person Update" : "Person Save")" />
</form>

<h2>People</h2>
<hr />
<form class="form-inline mb-2" asp-action="Query" method="Get">

    <input class="form-control mr-2 mt-3" name="name" />
    <input type="submit" class="btn btn-secondary mt-2" value="Query" />
</form>
<table class="table table-bordered">
    <tr>
        <th>User Id</th>
        <th>City</th>
        <th>Name</th>
        <th>writing Paths</th>
        <th>Actions</th>
    </tr>

    @foreach (var item in ViewBag.people as List<MT.AzureStorageLib.Entities.UserPicture>)
    {
        <tr>
            <td>@item.RowKey</td>
            <td>@item.PartitionKey</td>
            <td>@item.Name</td>
            <td>@item.WritingRawPaths</td>

            <td>
                <a class="btn btn-success mr-1 btn-sm" asp-action="Update" asp-controller="TableStorages" asp-route-rowKey="@item.RowKey" asp-route-partitionKey="@item.PartitionKey">Update</a>
                <a class="btn btn-danger btn-sm" asp-action="Delete" asp-controller="TableStorages" asp-route-rowKey="@item.RowKey" asp-route-partitionKey="@item.PartitionKey">Delete</a>
            </td>
        </tr>

    }
</table>